[build]
  command = "hugo --gc --minify"
  publish = "public" 

  [context.production.environment]
    HUGO_ENV = "production"
  
  [context.deploy-preview]
    command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

  [context.branch-deploy]
    command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/*"
  to = "/"

  status = 302
